fix compatibility issues
Previously, this flake threw the following error:
 ```
error: Unexpected files in /etc, aborting activation
The following files have unrecognized content and would be overwritten:

  /etc/nix/nix.conf

Please check there is nothing critical in these files, rename them by adding .before-nix-darwin to the end, and then try again.
```

This is due to installation of nix via the determinate systems distribution. To resolve this issue, I disabled nix maangement by this flake.